### ISSUE TITLE
Error in errorMiddleware.js when running backend server

### ISSUE THREAD

**Issue by uyriq** [Chinwike1/redux-user-auth#3]
Description: I followed the tutorial on blogrocket to set up the redux-user-auth project, but I encountered some errors when I tried to run the backend server. 

The error message I got on localhost:5000 was:
```
Error: Not found: /
at errorHandler (file:///C:/Users/qqq/proj/redux-user-auth/backend/middleware/errorMiddleware.js:13:17)
at Layer.handle [as handle_request] (C:\Users\qqq\proj\redux-user-auth\node_modules\express\lib\router\layer.js:95:5)
at trim_prefix (C:\Users\qqq\proj\redux-user-auth\node_modules\express\lib\router\index.js:328:13)
at C:\Users\qqq\proj\redux-user-auth\node_modules\express\lib\router\index.js:286:9
at Function.process_params (C:\Users\qqq\proj\redux-user-auth\node_modules\express\lib\router\index.js:346:12)
at next (C:\Users\qqq\proj\redux-user-auth\node_modules\express\lib\router\index.js:280:10)
at Layer.handle [as handle_request] (C:\Users\qqq\proj\redux-user-auth\node_modules\express\lib\router\layer.js:91:12)
at trim_prefix (C:\Users\qqq\proj\redux-user-auth\node_modules\express\lib\router\index.js:328:13)
at C:\Users\qqq\proj\redux-user-auth\node_modules\express\lib\router/index.js:286:9
at Function.process_params (C:\Users/qqq/proj/redux-user-auth/node_modules/express/lib/router/index.js:346:12)
```
I also noticed that my database on MongoDB Atlas was empty, even though I filled out the form on the frontend part. Here are some screenshots of the database and the form:

![image](https://github.com/Chinwike1/redux-user-auth/assets/105006434/d5865ef9-1470-4d0f-b0f7-bb55e6de78ff)

![image](https://github.com/Chinwike1/redux-user-auth/assets/105006434/1b5ccceb-9c16-4a84-8cdc-e3a7a10b6ef4)
 
on click event on login button (also why login on register page?)  there are not any fetch to atlas 
I would appreciate any help or guidance on how to fix this issue. Thank you.

**Comment by uyriq** [comment]
after clone main branch the buton register apears well, but what is 
```
s://redux-user-auth.up.railway.app/api/user/register' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xhr.js:220   
        POST https://redux-user-auth.up.railway.app/api/user/register net::ERR_FAILED
(anonymous) @ xhr.js:220
e.exports @ xhr.js:16
e.exports @ dispatchReq
```
due to this failed fetch, no changes to mongodb
it seems that readme.md missed about setup an intermediate app on railway.app hosting?

**Comment by Chinwike1** [comment]
Hi @uyriq, thank you for raising these issues!

I'll go over your errors in the sequence you presented them

### 1. `Error: Not found: /` when trying to access the route `http://localhost:5000/`
The reason why this error occurs is because the route `http://localhost:5000/` is not defined in `server.js`. The only available routes on this server are: `/api/user/<register | login | profile>`

### 2. Railway URL CORS error
Apologies for this error I accidentally included the prod URL (`https://redux-user-auth.up.railway.app/api/user/register`) in the codebase for testing and forgot to remove it afterwards. To fix this, in `authActions.js`, delete the first line and uncomment the line below it:
```javascript
  const backendURL = 'https://redux-user-auth.up.railway.app' // delete this line and use the line below
  // const backendURL = 'http://127.0.0.1:5000'
```
This will ensure that the Register button sends requests to the local server at http://localhost:5000 and create a new entry in your Mongo Database — if everything else is set up right.

I'll create a fix soon that detects the current node environment and sets the appropriate server URL for making fetch requests too. Something like this:
```javascript
  const backendURL =
    process.env.NODE_ENV !== 'production'
      ? 'http://127.0.0.1:5000/'
      : process.env.SERVER_PROD_URL
```

### 3. Wrong copy on Register button on Register screen?
You mentioned this:
> on click event on login button (also why login on register page?)

That's weird because it shows [here](https://github.com/Chinwike1/redux-user-auth/blob/de9268e3b2a918d1447f34aacfe8c634f64806b1/frontend/src/screens/RegisterScreen.js#L80) that the copy on the Register button is accurate. Maybe you made a local edit? 

Please feel free to share any other challenges or bugs you encounter.

**Comment by uyriq** [comment]
Thank you for the explanations, thanks to them I was able to move on, namely the user is created in the mongodb database, according to the values filled in the form, but still now a new problem has occurred.  I can't log in as this already registered user.
please see the steps that I follow
![Screenshot 2023-05-18 231312](https://github.com/Chinwike1/redux-user-auth/assets/105006434/9442fdb5-e7be-4ebc-9476-555b811839b9)
  there is mongodb after user creation. all right,
  next i try to log in with this user
![Screenshot 2023-05-18 234229](https://github.com/Chinwike1/redux-user-auth/assets/105006434/e325b1a2-ef1b-4833-8b82-688b06bc9c60)
but stuck (see partly redux state on screen) 
the next error apear in console 
![Screenshot 2023-05-18 233249](https://github.com/Chinwike1/redux-user-auth/assets/105006434/4f5e5176-6ad8-4551-9ede-366476b33d9d)
![Screenshot 2023-05-18 233025](https://github.com/Chinwike1/redux-user-auth/assets/105006434/f1882245-e1eb-417e-82a9-223f95ce1eb9)
the complete state of redux store as JSON
```JSON
{
	"payload": "[{\"type\":\"authApi/executeQuery/pending\",\"meta\":{\"startedTimeStamp\":1684442433903,\"arg\":{\"type\":\"query\",\"subscribe\":true,\"subscriptionOptions\":{\"pollingInterval\":900000},\"endpointName\":\"getDetails\",\"originalArgs\":\"userDetails\",\"queryCacheKey\":\"getDetails(\\\"userDetails\\\")\"},\"requestId\":\"b_lJuS3gm3RtoYIuWlh38\",\"requestStatus\":\"pending\"}},{\"type\":\"authApi/executeQuery/rejected\",\"meta\":{\"arg\":{\"type\":\"query\",\"subscribe\":true,\"subscriptionOptions\":{\"pollingInterval\":900000},\"endpointName\":\"getDetails\",\"originalArgs\":\"userDetails\",\"queryCacheKey\":\"getDetails(\\\"userDetails\\\")\"},\"requestId\":\"BhRfpf8HlkZzGx5WECluQ\",\"rejectedWithValue\":false,\"requestStatus\":\"rejected\",\"aborted\":false,\"condition\":true},\"error\":{\"name\":\"ConditionError\",\"message\":\"Aborted due to condition callback returning false.\"}},{\"type\":\"authApi/executeQuery/rejected\",\"meta\":{\"arg\":{\"type\":\"query\",\"subscribe\":true,\"subscriptionOptions\":{\"pollingInterval\":900000},\"endpointName\":\"getDetails\",\"originalArgs\":\"userDetails\",\"queryCacheKey\":\"getDetails(\\\"userDetails\\\")\"},\"requestId\":\"b_lJuS3gm3RtoYIuWlh38\",\"rejectedWithValue\":false,\"requestStatus\":\"rejected\",\"aborted\":false,\"condition\":false},\"error\":{\"name\":\"TypeError\",\"message\":\"Cannot read properties of undefined (reading 'has')\",\"stack\":\"TypeError: Cannot read properties of undefined (reading 'has')\\n    at http://localhost:3000/static/js/bundle.js:3014:33\\n    at step (http://localhost:3000/static/js/bundle.js:2694:17)\\n    at Object.next (http://localhost:3000/static/js/bundle.js:2625:14)\\n    at fulfilled (http://localhost:3000/static/js/bundle.js:2762:24)\"}},{\"type\":\"user/login/pending\",\"meta\":{\"arg\":{\"email\":\"spacedancer1337@nomoreparties.space\",\"password\":\"1111\"},\"requestId\":\"Ikx1_blOS9tiCo6aGKHnt\",\"requestStatus\":\"pending\"}},{\"type\":\"user/login/rejected\",\"payload\":\"secretOrPrivateKey must have a value\",\"meta\":{\"arg\":{\"email\":\"spacedancer1337@nomoreparties.space\",\"password\":\"1111\"},\"requestId\":\"Ikx1_blOS9tiCo6aGKHnt\",\"rejectedWithValue\":true,\"requestStatus\":\"rejected\",\"aborted\":false,\"condition\":false},\"error\":{\"message\":\"Rejected\"}}]"
}

```
on a network tab i see response to login fetch as follow


![Screenshot 2023-05-19 000654](https://github.com/Chinwike1/redux-user-auth/assets/105006434/bce3dc4a-64e0-4739-baba-1a0bac0ef9e6)
I don't ivestigate yet further about this `\"type\":\"user/login/rejected\",\"
payload\":\"secretOrPrivateKey must have a value\",\"meta\": `

please see the steps that I follow
and share your thoughts.

**Comment by Chinwike1** [comment]
Hi @uyriq,

Apologies for the late reply. I've examined your problem and I think what causes the `secretOrPrivateKey must have a value` error is that the app isn't recognizing the environment variables. Is your .env file set up correctly? I left a snippet of what it should look like in the readme.md. Please check [generateToken.js](https://github.com/Chinwike1/redux-user-auth/blob/main/backend/utils/generateToken.js) to confirm that your jwt secret is accessible. 

Also, when a user is created, the server sends a token which is saved in localStorage and redux store. Check if this token is present after registration. I'll be waiting on your feedback

**Comment by uyriq** [comment]
Thanks! 
![image](https://github.com/Chinwike1/redux-user-auth/assets/105006434/ea0c1e59-3a83-4d2e-b328-3e7f6eba3d0e)
I apologize for the mistake I made earlier. I accidentally left `JWT_SECRET = ' '` in the .env file. all fixed, close!

**Comment by uyriq** [comment]
I noticed that the token does not expire before 12 hours, even if I set the JWT_EXPIRES_IN environment variable to '1m'.  How can I change the code to make the token expire according to the environment variable? I tried this:
 ```Javascript 
 const generateToken = (id) => {
  return jwt.sign({ id }, (process.env.JWT_SECRET||'basic_secret'), { expiresIn: process.env.JWT_EXPIRES_IN || '12h' })
}
```

**Comment by Chinwike1** [comment]
Your syntax is correct. But '1m' isn't recognized as a minute by JWT since 'm' is not a valid time descriptor. Take a look at the examples [here](https://github.com/vercel/ms) to see valid time formats.
